# Generated by Django 3.2.16 on 2022-10-22 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(db_column='id_course', on_delete=django.db.models.deletion.DO_NOTHING, to='core.course')),
                ('student', models.ForeignKey(db_column='id_student', on_delete=django.db.models.deletion.DO_NOTHING, to='core.student')),
            ],
            options={
                'db_table': 'student_course',
                'managed': True,
                'unique_together': {('student', 'course')},
            },
        ),
    ]
