# Generated by Django 4.0.4 on 2022-05-26 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_asd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='asd',
        ),
    ]
